"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, ExternalLink, MoreHorizontal, Pencil, Plus, Search, Settings2, ShoppingBasket, Sparkles, Trash2, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

type Meal = { day: number; main: string; sides: string[]; type: string; color: string };
type Recipe = { id: number | string; emoji: string; color: string; title: string; meta: string; tags: string[]; sourceUrl?: string | null; sourceTitle?: string | null; sourceAuthor?: string | null };
type Grocery = { id: number | string; name: string; category: string; done: boolean };
type AgentRequest = { prompt: string; action: "PUBLISH_WEEK" | "UPDATE_DAY"; date?: string };
type MealSnapshot = { date: string; lunch?: string | null; main: string; sides: string[]; baby?: string | null; note?: string | null; changeReason?: string | null };
type DayUpdateResult = { changed: boolean; before: MealSnapshot | null; after: MealSnapshot | null };
const nav = [[CalendarDays, "이 달의 식단"], [BookOpen, "레시피"], [ShoppingBasket, "장보기"], [UsersRound, "우리 가족"]] as const;
const seedMeals: Meal[] = [];
const seedRecipes: Recipe[] = [];
const seedGrocery: Grocery[] = [];
const days = Array.from({ length: 35 }, (_, i) => i - 3);

export default function Home() {
  const [view, setView] = useState<"month" | "week">("month");
  const [active, setActive] = useState<(typeof nav)[number][1]>("이 달의 식단");
  const [agentRequest, setAgentRequest] = useState<AgentRequest | null>(null);
  const [mealItems, setMealItems] = useState(seedMeals);
  const [recipes, setRecipes] = useState(seedRecipes);
  const [grocery, setGrocery] = useState(seedGrocery);

  useEffect(() => {
    const load = () => fetch("/api/meal-data?month=2026-09&week=2026-08-30")
      .then((response) => response.ok ? response.json() : Promise.reject(new Error("식단을 불러오지 못했습니다.")))
      .then((data) => { setMealItems(data.meals ?? []); setRecipes(data.recipes ?? []); setGrocery(data.grocery ?? []); })
      .catch(() => { setMealItems([]); setRecipes([]); setGrocery([]); });
    load();
    const timer = window.setInterval(load, 30_000);
    return () => window.clearInterval(timer);
  }, []);

  return <main className="min-h-screen lg:flex"><aside className="app-sidebar fixed inset-y-0 w-[252px] border-r border-black/[.08] bg-white px-4 py-5"><div className="mb-9 flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#ffb110] text-xl">🍽️</div><div><p className="text-[15px] font-semibold">우리집 식탁</p><p className="text-xs text-black/45">우리 세 식구</p></div></div><div className="space-y-1">{nav.map(([Icon, label]) => <button key={label} onClick={() => setActive(label)} className={`sidebar-link ${active === label ? "active" : ""}`}><Icon size={18}/>{label}</button>)}</div><div className="mt-8 border-t border-black/[.07] pt-5"><p className="px-3 pb-2 text-[11px] font-semibold tracking-[.08em] text-black/35">SMART PLANNING</p><button onClick={() => setAgentRequest({ action: "PUBLISH_WEEK", prompt: "이번 주 가족 일정, 식비, 보유 재료를 확인하고 필요한 메뉴만 조정한 뒤 주찬과 부찬의 검증된 블로그 레시피 및 장보기를 게시해줘." })} className="sidebar-link"><Sparkles size={18} className="text-[#e89d01]"/>AI 식단 제안</button></div><div className="absolute bottom-5 left-4 right-4"><button className="sidebar-link"><Settings2 size={18}/>설정</button><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#f6f5f4] p-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#0975de] text-xs text-white">우</span><span className="text-sm font-medium">우진 님</span><MoreHorizontal className="ml-auto text-black/40" size={17}/></div></div></aside><section className="min-w-0 flex-1 lg:ml-[252px]"><div className="mx-auto max-w-[1440px] p-5 md:p-9">{active === "이 달의 식단" && <MealPlanner view={view} setView={setView} meals={mealItems} onEditDay={(day) => setAgentRequest({ action: "UPDATE_DAY", date: `2026-09-${String(day).padStart(2, "0")}`, prompt: `${day}일 식단을 가족 일정과 보유 재료에 맞게 수정하고, 변경된 주찬과 부찬의 검증된 블로그 레시피 및 장보기를 다시 게시해줘.` })}/>} {active === "레시피" && <Recipes recipes={recipes} setRecipes={setRecipes}/>} {active === "장보기" && <GroceryList grocery={grocery} setGrocery={setGrocery}/>} {active === "우리 가족" && <Family/>}</div></section>{agentRequest && <AgentModal request={agentRequest} close={() => setAgentRequest(null)}/>}</main>;
}

function PageTitle({ label, title, children }: { label: string; title: string; children?: React.ReactNode }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm text-black/45">{label}</p><h1 className="text-[28px] font-semibold tracking-[-.035em] md:text-[32px]">{title}</h1></div>{children}</div>; }
function MealPlanner({ view, setView, meals, onEditDay }: { view: "month" | "week"; setView: (v: "month" | "week") => void; meals: Meal[]; onEditDay: (day: number) => void }) { return <><PageTitle label="식단 플래너" title="9월의 식단"><div className="flex rounded-lg border border-black/[.08] bg-white p-1"><button onClick={() => setView("month")} className={`rounded-md px-3 py-1.5 text-sm ${view === "month" ? "bg-[#e6f3fe] text-[#0075de]" : "text-black/50"}`}>월간</button><button onClick={() => setView("week")} className={`rounded-md px-3 py-1.5 text-sm ${view === "week" ? "bg-[#e6f3fe] text-[#0075de]" : "text-black/50"}`}>주간</button></div></PageTitle><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-black/[.08] px-5 py-4"><div className="flex items-center gap-3"><button className="rounded-md p-1.5 hover:bg-black/[.04]"><ChevronLeft size={18}/></button><h2 className="font-semibold">2026년 9월</h2><button className="rounded-md p-1.5 hover:bg-black/[.04]"><ChevronRight size={18}/></button></div><Button variant="outline" size="sm"><Plus size={15}/>식단 추가</Button></div>{view === "month" ? <MonthView meals={meals} onEditDay={onEditDay}/> : <WeekView meals={meals} onEditDay={onEditDay}/>}</Card></>; }
function MealCard({ meal, onEdit }: { meal: Meal; onEdit: () => void }) { return <div className={`group relative mt-2 rounded-md px-2 py-1.5 text-[11px] leading-tight ${meal.color}`}><button type="button" onClick={onEdit} className="absolute right-1 top-1 rounded p-1 text-black/35 opacity-0 hover:bg-white/70 hover:text-[#0075de] group-hover:opacity-100 focus:opacity-100" aria-label={`${meal.day}일 식단 수정`}><Pencil size={12}/></button><span className="block pr-5 text-black/45">{meal.type}</span><b className="block font-medium">주찬 · {meal.main}</b>{meal.sides.map(side => <span key={side} className="mt-0.5 block text-black/60">부찬 · {side}</span>)}</div>; }
function MonthView({ meals, onEditDay }: { meals: Meal[]; onEditDay: (day: number) => void }) { return <div className="grid grid-cols-7">{["일","월","화","수","목","금","토"].map(x => <div className="border-b border-r border-black/[.08] px-3 py-2 text-xs font-medium text-black/40" key={x}>{x}</div>)}{days.map((date, i) => { const meal = meals.find(m => m.day === date); return <div className={`calendar-cell ${date < 1 || date > 30 ? "bg-black/[.015] text-black/30" : ""}`} key={i}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs ${date === 5 ? "bg-[#0075de] text-white" : ""}`}>{date < 1 ? 31 + date : date > 30 ? date - 30 : date}</span>{meal && <MealCard meal={meal} onEdit={() => onEditDay(meal.day)}/>}</div>})}</div>; }
function WeekView({ meals, onEditDay }: { meals: Meal[]; onEditDay: (day: number) => void }) { return <div className="grid grid-cols-7">{["일","월","화","수","목","금","토"].map((d, i) => { const meal = meals.find(m => m.day === i + 1); return <div key={d} className="min-h-[420px] border-r border-black/[.08] p-3 last:border-0"><p className="text-center text-xs text-black/45">{d}</p><p className={`mx-auto mt-2 grid h-7 w-7 place-items-center rounded-full text-sm ${i === 5 ? "bg-[#0075de] text-white" : ""}`}>{i + 1}</p>{meal && <MealCard meal={meal} onEdit={() => onEditDay(meal.day)}/>}</div>})}</div>; }
function Recipes({ recipes, setRecipes }: { recipes: Recipe[]; setRecipes: React.Dispatch<React.SetStateAction<Recipe[]>> }) { const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false); const [title, setTitle] = useState(""); const filtered = useMemo(() => recipes.filter(r => r.title.includes(query) || r.tags.some(t => t.includes(query))), [query, recipes]); const add = () => { if (!title.trim()) return; setRecipes(items => [{ id: Date.now(), emoji: "🍲", color: "bg-[#e6f3fe]", title, meta: "성인 2명 · 아기 1명", tags: ["내 레시피"] }, ...items]); setTitle(""); setAdding(false); }; return <><PageTitle label="우리집 레시피" title="레시피"><Button onClick={() => setAdding(!adding)}><Plus size={16}/>레시피 추가</Button></PageTitle>{adding && <Card className="mb-5"><CardContent className="flex flex-wrap gap-3"><input autoFocus value={title} onChange={e => setTitle(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} className="h-9 min-w-[220px] flex-1 rounded-lg border border-black/10 px-3 text-sm outline-none focus:border-[#0075de]" placeholder="레시피 이름을 입력하세요"/><Button onClick={add}>저장</Button><Button variant="ghost" onClick={() => setAdding(false)}>취소</Button></CardContent></Card>}<div className="mb-5 flex max-w-md items-center gap-2 rounded-lg border border-black/[.1] bg-white px-3"><Search size={17} className="text-black/40"/><input value={query} onChange={e => setQuery(e.target.value)} className="h-10 w-full bg-transparent text-sm outline-none" placeholder="레시피 또는 태그 검색"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(recipe => <Card key={recipe.id} className="overflow-hidden"><div className={`grid h-32 place-items-center text-5xl ${recipe.color}`}>{recipe.emoji}</div><CardContent className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{recipe.title}</p><p className="mt-1 text-sm text-black/45">{recipe.meta}</p></div><button onClick={() => setRecipes(items => items.filter(r => r.id !== recipe.id))} className="p-1 text-black/35 hover:text-[#e32d14]" aria-label={`${recipe.title} 삭제`}><Trash2 size={16}/></button></div><div className="mt-3 flex flex-wrap gap-1">{recipe.tags.map(tag => <span key={tag} className="rounded-full bg-[#f6f5f4] px-2 py-1 text-[11px] text-black/55">{tag}</span>)}</div>{recipe.sourceUrl && <a href={recipe.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 flex items-center gap-1 text-xs font-medium text-[#0075de] hover:underline" title={recipe.sourceTitle ?? undefined}><ExternalLink size={13}/>{recipe.sourceAuthor ? `${recipe.sourceAuthor} 블로그 원문` : "블로그 원문 보기"}</a>}</CardContent></Card>)}</div></>; }
function GroceryList({ grocery, setGrocery }: { grocery: Grocery[]; setGrocery: React.Dispatch<React.SetStateAction<Grocery[]>> }) { const [name, setName] = useState(""); const [category, setCategory] = useState("기타"); const remaining = grocery.filter(i => !i.done).length; const add = () => { if (!name.trim()) return; setGrocery(items => [...items, { id: Date.now(), name, category, done: false }]); setName(""); }; const groups = grocery.reduce<Record<string, Grocery[]>>((acc, item) => ({ ...acc, [item.category]: [...(acc[item.category] ?? []), item] }), {}); return <><PageTitle label="이번 주 필요한 재료" title="장보기"><span className="text-sm text-black/45">{remaining}개 남음</span></PageTitle><Card><CardContent><div className="mb-6 flex flex-wrap gap-2"><input value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} className="h-9 min-w-[180px] flex-1 rounded-lg border border-black/10 px-3 text-sm outline-none focus:border-[#0075de]" placeholder="장보기 품목 입력"/><select value={category} onChange={e => setCategory(e.target.value)} className="h-9 rounded-lg border border-black/10 bg-white px-3 text-sm"><option>채소</option><option>정육</option><option>유제품</option><option>냉장</option><option>양념</option><option>기타</option></select><Button onClick={add}><Plus size={16}/>추가</Button></div>{Object.entries(groups).map(([group, items]) => <section key={group} className="mb-6 last:mb-0"><p className="mb-2 text-xs font-semibold tracking-[.08em] text-black/40">{group.toUpperCase()}</p>{items.map(item => <div className="flex items-center gap-3 border-t border-black/[.07] py-3" key={item.id}><button onClick={() => setGrocery(all => all.map(i => i.id === item.id ? { ...i, done: !i.done } : i))} className={`grid h-5 w-5 place-items-center rounded border ${item.done ? "border-[#0075de] bg-[#0075de] text-white" : "border-black/20"}`}>{item.done && <Check size={13}/>}</button><span className={`flex-1 text-sm ${item.done ? "text-black/35 line-through" : ""}`}>{item.name}</span><button onClick={() => setGrocery(all => all.filter(i => i.id !== item.id))} className="text-black/30 hover:text-[#e32d14]" aria-label={`${item.name} 삭제`}><Trash2 size={16}/></button></div>)}</section>)}</CardContent></Card></>; }
function Family() { return <><PageTitle label="식단 기준을 함께 관리해요" title="우리 가족"/><Card><CardContent><p className="font-medium">가족 구성원 기능은 다음 단계로 준비 중이에요.</p><p className="mt-2 text-sm text-black/50">구성원의 알레르기, 선호 음식과 식사량을 등록하면 AI 식단 추천에 반영됩니다.</p></CardContent></Card></>; }
function AgentModal({ request, close }: { request: AgentRequest; close: () => void }) {
  const [prompt, setPrompt] = useState(request.prompt);
  const [message, setMessage] = useState("");
  const [result, setResult] = useState<DayUpdateResult | null>(null);
  const [loading, setLoading] = useState(false);
  const createPlan = async () => {
    if (!prompt.trim()) return;
    setLoading(true); setMessage(""); setResult(null);
    try {
      const response = await fetch("/api/agent/meal-plan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, action: request.action, date: request.date, weekStart: "2026-08-30", days: request.action === "UPDATE_DAY" ? 1 : 7 }) });
      const data = await response.json();
      setMessage(response.ok ? data.message : data.message ?? data.error ?? "Hermes 요청에 실패했습니다.");
      if (response.ok && data.result) setResult(data.result);
    } catch { setMessage("Hermes에 연결할 수 없습니다."); }
    finally { setLoading(false); }
  };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4"><Card className="w-full max-w-xl"><CardContent><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0d4]"><Sparkles className="text-[#e89d01]" size={20}/></div><button onClick={close} className="text-xl text-black/35">×</button></div><h2 className="mt-5 text-2xl font-semibold tracking-tight">Hermes에게 식단을 부탁해 보세요</h2><p className="mt-2 text-sm leading-5 text-black/55">{request.date ? `${request.date} 식단과 관련 레시피·장보기를 수정합니다.` : "이번 주 식단과 검증된 블로그 레시피·장보기를 준비합니다."}</p><textarea value={prompt} onChange={e => setPrompt(e.target.value)} className="mt-5 h-28 w-full resize-none rounded-lg border border-black/[.12] p-3 text-sm outline-none focus:border-[#0075de]"/><Button disabled={!prompt.trim() || loading} onClick={createPlan} className="mt-3 w-full"><Sparkles size={16}/>{loading ? "Hermes가 확인하고 있어요..." : "Hermes에 요청하기"}</Button>{message && <div className="mt-4 rounded-lg bg-[#e6f3fe] p-3 text-sm text-[#075f9f]">{message}</div>}{result && <div className="mt-4 grid gap-3 sm:grid-cols-2"><MealSnapshotCard label="변경 전" meal={result.before}/><MealSnapshotCard label={result.changed ? "변경 후" : "유지"} meal={result.after} highlight={result.changed}/></div>}<p className="mt-3 text-center text-[11px] text-black/40">완료된 변경은 레시피와 장보기 탭에도 자동으로 표시됩니다.</p></CardContent></Card></div>;
}

function MealSnapshotCard({ label, meal, highlight = false }: { label: string; meal: MealSnapshot | null; highlight?: boolean }) {
  return <div className={`rounded-xl border p-3 ${highlight ? "border-[#0075de]/30 bg-[#e6f3fe]" : "border-black/[.08] bg-white"}`}><p className="text-xs font-semibold text-black/40">{label}</p>{meal ? <><p className="mt-2 font-medium">주찬 · {meal.main}</p>{meal.sides.map((side) => <p key={side} className="mt-1 text-sm text-black/60">부찬 · {side}</p>)}{meal.baby && <p className="mt-2 text-xs text-black/50">아기 · {meal.baby}</p>}{meal.changeReason && <p className="mt-2 text-xs text-[#075f9f]">이유 · {meal.changeReason}</p>}</> : <p className="mt-2 text-sm text-black/45">식단 정보 없음</p>}</div>;
}
