"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, ExternalLink, Menu, MoreHorizontal, Pencil, Plus, Search, ShoppingBasket, Sparkles, Trash2, UsersRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

type Meal = { day: number; main: string; sides: string[]; type: string; color: string };
type Recipe = { id: number | string; emoji: string; color: string; title: string; meta: string; tags: string[]; sourceUrl?: string | null; sourceTitle?: string | null; sourceAuthor?: string | null };
type Grocery = { id: number | string; name: string; category: string; done: boolean };
type AgentRequest = { prompt: string; action: "PUBLISH_WEEK" | "UPDATE_DAY"; date?: string };
type MealSnapshot = { date: string; lunch?: string | null; main: string; sides: string[]; baby?: string | null; note?: string | null; changeReason?: string | null };
type DayUpdateResult = { changed: boolean; before: MealSnapshot | null; after: MealSnapshot | null };
type DayDetail = { date: string; meal: { lunch?: string | null; main?: string | null; sides: string[]; baby?: string | null; note?: string | null } | null; fatherSchedule: { isWorking: boolean; eatsAtCompany: boolean; isAway: boolean; note: string } };
const nav = [[CalendarDays, "이 달의 식단"], [BookOpen, "레시피"], [ShoppingBasket, "장보기"], [UsersRound, "우리 가족"]] as const;
const seedMeals: Meal[] = [];
const seedRecipes: Recipe[] = [];
const seedGrocery: Grocery[] = [];

export default function Home() {
  const [view, setView] = useState<"month" | "week">("month");
  const [active, setActive] = useState<(typeof nav)[number][1]>("이 달의 식단");
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [agentRequest, setAgentRequest] = useState<AgentRequest | null>(null);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [mealItems, setMealItems] = useState(seedMeals);
  const [recipes, setRecipes] = useState(seedRecipes);
  const [grocery, setGrocery] = useState(seedGrocery);
  const [selectedMonth, setSelectedMonth] = useState("2026-09");

  useEffect(() => {
    const load = () => fetch(`/api/meal-data?month=${selectedMonth}&week=${sundayFor(`${selectedMonth}-01`)}`)
      .then((response) => response.ok ? response.json() : Promise.reject(new Error("식단을 불러오지 못했습니다.")))
      .then((data) => { setMealItems(data.meals ?? []); setRecipes(data.recipes ?? []); setGrocery(data.grocery ?? []); })
      .catch(() => { setMealItems([]); setRecipes([]); setGrocery([]); });
    load();
    const timer = window.setInterval(load, 30_000);
    return () => window.clearInterval(timer);
  }, [selectedMonth]);

  return (
    <main className="min-h-screen lg:flex">
      <header className="fixed inset-x-0 top-0 z-30 flex h-16 items-center justify-between border-b border-black/[.08] bg-[#f6f5f4]/95 px-5 backdrop-blur lg:hidden">
        <div className="flex items-center gap-2.5"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#ffb110] text-base">🍽️</div><span className="text-sm font-semibold">우리집 식탁</span></div>
        <button type="button" onClick={() => setMobileNavOpen(true)} className="grid h-11 w-11 place-items-center rounded-lg text-black/65 transition-transform duration-200 hover:bg-black/[.05] active:scale-95 focus:outline-none focus:ring-2 focus:ring-[#0075de]/40" aria-label="메뉴 열기"><Menu size={22}/></button>
      </header>
      <button type="button" className={`fixed inset-0 z-30 block bg-black/25 transition-opacity duration-300 ease-out lg:hidden ${mobileNavOpen ? "pointer-events-auto opacity-100" : "pointer-events-none opacity-0"}`} onClick={() => setMobileNavOpen(false)} aria-label="메뉴 닫기"/>
      <aside className={`app-sidebar fixed inset-y-0 z-40 w-[252px] border-r border-black/[.08] bg-white px-4 py-5 shadow-xl transition-[transform,width] duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] lg:translate-x-0 lg:shadow-none ${sidebarCollapsed ? "lg:w-[72px] lg:px-3" : "lg:w-[252px] lg:px-4"} ${mobileNavOpen ? "translate-x-0" : "-translate-x-full"}`}>
        <div className={`mb-9 flex items-center ${sidebarCollapsed ? "justify-center" : "justify-between px-2"}`}>
          <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#ffb110] text-xl">🍽️</div>{!sidebarCollapsed && <div><p className="text-[15px] font-semibold">우리집 식탁</p><p className="text-xs text-black/45">우리 세 식구</p></div>}</div>
          <button type="button" onClick={() => setMobileNavOpen(false)} className="grid h-11 w-11 place-items-center rounded-lg text-black/45 hover:bg-black/[.05] lg:hidden" aria-label="메뉴 닫기"><X size={20}/></button>
          <button type="button" onClick={() => setSidebarCollapsed((collapsed) => !collapsed)} className={`hidden rounded-md p-1.5 text-black/45 hover:bg-black/[.05] hover:text-black lg:flex ${sidebarCollapsed ? "absolute top-5 -right-3 z-10 border border-black/[.08] bg-white shadow-sm" : ""}`} aria-label={sidebarCollapsed ? "사이드바 펼치기" : "사이드바 접기"}>{sidebarCollapsed ? <ChevronRight size={16}/> : <ChevronLeft size={16}/>}</button>
        </div>
        <div className="space-y-1">{nav.map(([Icon, label]) => <button key={label} onClick={() => { setActive(label); setMobileNavOpen(false); }} title={sidebarCollapsed ? label : undefined} className={`sidebar-link ${active === label ? "active" : ""} ${sidebarCollapsed ? "justify-center px-0" : ""}`}><Icon size={18}/>{!sidebarCollapsed && label}</button>)}</div>
        <div className={`absolute bottom-5 ${sidebarCollapsed ? "left-3 right-3" : "left-4 right-4"}`}><div className={`flex items-center rounded-xl bg-[#f6f5f4] p-3 ${sidebarCollapsed ? "justify-center" : "gap-2"}`}><span className="grid h-7 w-7 place-items-center rounded-full bg-[#0975de] text-xs text-white">우</span>{!sidebarCollapsed && <><span className="text-sm font-medium">우진 님</span><MoreHorizontal className="ml-auto text-black/40" size={17}/></>}</div></div>
      </aside>
      <section className={`min-w-0 flex-1 pt-16 transition-[margin] duration-200 lg:pt-0 ${sidebarCollapsed ? "lg:ml-[72px]" : "lg:ml-[252px]"}`}><div className="mx-auto max-w-[1440px] p-5 md:p-9">
        {active === "이 달의 식단" && <MealPlanner view={view} setView={setView} month={selectedMonth} onChangeMonth={(amount) => setSelectedMonth((current) => shiftMonth(current, amount))} meals={mealItems} onOpenDay={setSelectedDate} onEditDay={(date) => setAgentRequest({ action: "UPDATE_DAY", date, prompt: `${date.slice(8)}일 식단을 가족 일정과 보유 재료에 맞게 수정하고, 변경된 주찬과 부찬의 검증된 블로그 레시피 및 장보기를 다시 게시해줘.` })}/>}
        {active === "레시피" && <Recipes recipes={recipes} setRecipes={setRecipes}/>}
        {active === "장보기" && <GroceryList grocery={grocery} setGrocery={setGrocery}/>}
        {active === "우리 가족" && <Family/>}
      </div></section>
      {selectedDate && <DayDetailModal date={selectedDate} close={() => setSelectedDate(null)}/>}
      {agentRequest && <AgentModal request={agentRequest} close={() => setAgentRequest(null)}/>}
    </main>
  );
}

function PageTitle({ label, title, children }: { label: string; title: string; children?: React.ReactNode }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm text-black/45">{label}</p><h1 className="text-[28px] font-semibold tracking-[-.035em] md:text-[32px]">{title}</h1></div>{children}</div>; }
function MealPlanner({ view, setView, month, onChangeMonth, meals, onOpenDay, onEditDay }: { view: "month" | "week"; setView: (v: "month" | "week") => void; month: string; onChangeMonth: (amount: number) => void; meals: Meal[]; onOpenDay: (date: string) => void; onEditDay: (date: string) => void }) { const weekDays = buildMonthDays(month).slice(0, 7); return <><PageTitle label="식단 플래너" title={`${month.slice(5)}월의 식단`}><div className="flex rounded-lg border border-black/[.08] bg-white p-1"><button onClick={() => setView("month")} className={`rounded-md px-3 py-1.5 text-sm ${view === "month" ? "bg-[#e6f3fe] text-[#0075de]" : "text-black/50"}`}>월간</button><button onClick={() => setView("week")} className={`rounded-md px-3 py-1.5 text-sm ${view === "week" ? "bg-[#e6f3fe] text-[#0075de]" : "text-black/50"}`}>주간</button></div></PageTitle><Card className="overflow-hidden"><div className="flex items-center border-b border-black/[.08] px-5 py-4"><div className="flex items-center gap-3"><button type="button" onClick={() => onChangeMonth(-1)} className="grid h-11 w-11 place-items-center rounded-lg hover:bg-black/[.04]" aria-label="이전 달"><ChevronLeft size={18}/></button><h2 className="font-semibold">{formatMonth(month)}</h2><button type="button" onClick={() => onChangeMonth(1)} className="grid h-11 w-11 place-items-center rounded-lg hover:bg-black/[.04]" aria-label="다음 달"><ChevronRight size={18}/></button></div></div>{view === "month" ? <><div className="lg:hidden"><MobileMealList days={buildMonthDays(month).filter((cell) => cell.current)} meals={meals} onOpenDay={onOpenDay}/></div><div className="hidden lg:block"><MonthView month={month} meals={meals} onOpenDay={onOpenDay} onEditDay={onEditDay}/></div></> : <><div className="lg:hidden"><MobileMealList days={weekDays} meals={meals} onOpenDay={onOpenDay}/></div><div className="hidden lg:block"><WeekView month={month} meals={meals} onOpenDay={onOpenDay} onEditDay={onEditDay}/></div></>}</Card></>; }
function MealCard({ meal, onEdit }: { meal: Meal; onEdit: () => void }) { return <div className={`group relative mt-2 rounded-md px-2 py-1.5 text-[11px] leading-tight break-keep ${meal.color}`}><button type="button" onClick={onEdit} className="absolute right-1 top-1 hidden h-8 w-8 place-items-center rounded text-black/35 hover:bg-white/70 hover:text-[#0075de] focus:grid lg:grid lg:opacity-0 lg:group-hover:opacity-100" aria-label={`${meal.day}일 식단 수정`}><Pencil size={12}/></button><span className="block pr-5 text-black/45">{meal.type}</span><b className="block font-medium">주찬 · {meal.main}</b>{meal.sides.map(side => <span key={side} className="mt-0.5 block text-black/60">부찬 · {side}</span>)}</div>; }
function MonthView({ month, meals, onOpenDay, onEditDay }: { month: string; meals: Meal[]; onOpenDay: (date: string) => void; onEditDay: (date: string) => void }) { const lastTap = useRef({ date: "", at: 0 }); const onTouch = (date: string) => { const now = Date.now(); if (lastTap.current.date === date && now - lastTap.current.at < 350) onOpenDay(date); lastTap.current = { date, at: now }; }; return <div className="grid min-w-[728px] grid-cols-7">{["일","월","화","수","목","금","토"].map(x => <div className="border-b border-r border-black/[.08] px-3 py-2 text-xs font-medium text-black/40" key={x}>{x}</div>)}{buildMonthDays(month).map((cell, index) => { const meal = cell.current ? meals.find((item) => item.day === cell.day) : undefined; return <div onDoubleClick={() => cell.current && onOpenDay(cell.date)} onTouchEnd={() => cell.current && onTouch(cell.date)} className={`calendar-cell touch-manipulation ${cell.current ? "cursor-pointer" : "bg-black/[.015] text-black/30"}`} key={`${cell.date}-${index}`}><span className="grid h-6 w-6 place-items-center rounded-full text-xs">{cell.day}</span>{meal && <MealCard meal={meal} onEdit={() => onEditDay(cell.date)}/>}</div>})}</div>; }
function MobileMealList({ days, meals, onOpenDay }: { days: ReturnType<typeof buildMonthDays>; meals: Meal[]; onOpenDay: (date: string) => void }) { return <div className="space-y-2 p-3">{days.map((cell) => { const meal = cell.current ? meals.find((item) => item.day === cell.day) : undefined; return <button type="button" key={cell.date} onClick={() => cell.current && onOpenDay(cell.date)} disabled={!cell.current} className={`flex w-full items-start gap-3 rounded-xl p-4 text-left transition-colors focus:outline-none focus:ring-2 focus:ring-[#0075de]/40 ${meal ? `${meal.color} hover:brightness-[.98]` : "bg-[#f6f5f4] text-black/35"}`} aria-label={cell.current ? `${cell.date} 식단 상세 보기` : `${cell.date} 이전 달 날짜`}><span className="min-w-10 pt-0.5 text-sm font-medium text-black/45">{weekdayFor(cell.date)}<br/>{cell.day}일</span>{meal ? <span className="min-w-0 flex-1"><b className="block break-keep text-[15px] leading-5">{meal.main}</b><span className="mt-1 block break-keep text-sm leading-5 text-black/60">{meal.sides.join(" · ")}</span></span> : <span className="pt-0.5 text-sm">{cell.current ? "식단 없음" : ""}</span>}</button>; })}</div>; }
function WeekView({ month, meals, onOpenDay, onEditDay }: { month: string; meals: Meal[]; onOpenDay: (date: string) => void; onEditDay: (date: string) => void }) { const lastTap = useRef({ date: "", at: 0 }); const onTouch = (date: string) => { const now = Date.now(); if (lastTap.current.date === date && now - lastTap.current.at < 350) onOpenDay(date); lastTap.current = { date, at: now }; }; const week = buildMonthDays(month).slice(0, 7); return <div className="grid grid-cols-7">{["일","월","화","수","목","금","토"].map((label, index) => { const cell = week[index]; const meal = cell.current ? meals.find((item) => item.day === cell.day) : undefined; return <div onDoubleClick={() => cell.current && onOpenDay(cell.date)} onTouchEnd={() => cell.current && onTouch(cell.date)} key={label} className={`min-h-[420px] touch-manipulation border-r border-black/[.08] p-3 last:border-0 ${cell.current ? "cursor-pointer" : "bg-black/[.015] text-black/30"}`}><p className="text-center text-xs text-black/45">{label}</p><p className="mx-auto mt-2 grid h-7 w-7 place-items-center rounded-full text-sm">{cell.day}</p>{meal && <MealCard meal={meal} onEdit={() => onEditDay(cell.date)}/>}</div>})}</div>; }
function Recipes({ recipes, setRecipes }: { recipes: Recipe[]; setRecipes: React.Dispatch<React.SetStateAction<Recipe[]>> }) { const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false); const [title, setTitle] = useState(""); const filtered = useMemo(() => recipes.filter(r => r.title.includes(query) || r.tags.some(t => t.includes(query))), [query, recipes]); const add = () => { if (!title.trim()) return; setRecipes(items => [{ id: Date.now(), emoji: "🍲", color: "bg-[#e6f3fe]", title, meta: "성인 2명 · 아기 1명", tags: ["내 레시피"] }, ...items]); setTitle(""); setAdding(false); }; return <><PageTitle label="우리집 레시피" title="레시피"><Button onClick={() => setAdding(!adding)}><Plus size={16}/>레시피 추가</Button></PageTitle>{adding && <Card className="mb-5"><CardContent className="flex flex-wrap gap-3"><input autoFocus value={title} onChange={e => setTitle(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} className="h-9 min-w-[220px] flex-1 rounded-lg border border-black/10 px-3 text-sm outline-none focus:border-[#0075de]" placeholder="레시피 이름을 입력하세요"/><Button onClick={add}>저장</Button><Button variant="ghost" onClick={() => setAdding(false)}>취소</Button></CardContent></Card>}<div className="mb-5 flex max-w-md items-center gap-2 rounded-lg border border-black/[.1] bg-white px-3"><Search size={17} className="text-black/40"/><input value={query} onChange={e => setQuery(e.target.value)} className="h-10 w-full bg-transparent text-sm outline-none" placeholder="레시피 또는 태그 검색"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(recipe => <Card key={recipe.id} className="overflow-hidden"><div className={`grid h-32 place-items-center text-5xl ${recipe.color}`}>{recipe.emoji}</div><CardContent className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{recipe.title}</p><p className="mt-1 text-sm text-black/45">{recipe.meta}</p></div><button onClick={() => setRecipes(items => items.filter(r => r.id !== recipe.id))} className="p-1 text-black/35 hover:text-[#e32d14]" aria-label={`${recipe.title} 삭제`}><Trash2 size={16}/></button></div><div className="mt-3 flex flex-wrap gap-1">{recipe.tags.map(tag => <span key={tag} className="rounded-full bg-[#f6f5f4] px-2 py-1 text-[11px] text-black/55">{tag}</span>)}</div>{recipe.sourceUrl && <a href={recipe.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 flex items-center gap-1 text-xs font-medium text-[#0075de] hover:underline" title={recipe.sourceTitle ?? undefined}><ExternalLink size={13}/>{recipe.sourceAuthor ? `${recipe.sourceAuthor} 블로그 원문` : "블로그 원문 보기"}</a>}</CardContent></Card>)}</div></>; }
function GroceryList({ grocery, setGrocery }: { grocery: Grocery[]; setGrocery: React.Dispatch<React.SetStateAction<Grocery[]>> }) { const [name, setName] = useState(""); const [category, setCategory] = useState("기타"); const remaining = grocery.filter(i => !i.done).length; const add = () => { if (!name.trim()) return; setGrocery(items => [...items, { id: Date.now(), name, category, done: false }]); setName(""); }; const groups = grocery.reduce<Record<string, Grocery[]>>((acc, item) => ({ ...acc, [item.category]: [...(acc[item.category] ?? []), item] }), {}); return <><PageTitle label="이번 주 필요한 재료" title="장보기"><span className="text-sm text-black/45">{remaining}개 남음</span></PageTitle><Card><CardContent><div className="mb-6 flex flex-wrap gap-2"><input value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} className="h-9 min-w-[180px] flex-1 rounded-lg border border-black/10 px-3 text-sm outline-none focus:border-[#0075de]" placeholder="장보기 품목 입력"/><select value={category} onChange={e => setCategory(e.target.value)} className="h-9 rounded-lg border border-black/10 bg-white px-3 text-sm"><option>채소</option><option>정육</option><option>유제품</option><option>냉장</option><option>양념</option><option>기타</option></select><Button onClick={add}><Plus size={16}/>추가</Button></div>{Object.entries(groups).map(([group, items]) => <section key={group} className="mb-6 last:mb-0"><p className="mb-2 text-xs font-semibold tracking-[.08em] text-black/40">{group.toUpperCase()}</p>{items.map(item => <div className="flex items-center gap-3 border-t border-black/[.07] py-3" key={item.id}><button onClick={() => setGrocery(all => all.map(i => i.id === item.id ? { ...i, done: !i.done } : i))} className={`grid h-5 w-5 place-items-center rounded border ${item.done ? "border-[#0075de] bg-[#0075de] text-white" : "border-black/20"}`}>{item.done && <Check size={13}/>}</button><span className={`flex-1 text-sm ${item.done ? "text-black/35 line-through" : ""}`}>{item.name}</span><button onClick={() => setGrocery(all => all.filter(i => i.id !== item.id))} className="text-black/30 hover:text-[#e32d14]" aria-label={`${item.name} 삭제`}><Trash2 size={16}/></button></div>)}</section>)}</CardContent></Card></>; }
function Family() { return <><PageTitle label="식단 기준을 함께 관리해요" title="우리 가족"/><Card><CardContent><p className="font-medium">가족 구성원 기능은 다음 단계로 준비 중이에요.</p><p className="mt-2 text-sm text-black/50">구성원의 알레르기, 선호 음식과 식사량을 등록하면 AI 식단 추천에 반영됩니다.</p></CardContent></Card></>; }
function DayDetailModal({ date, close }: { date: string; close: () => void }) {
  const [detail, setDetail] = useState<DayDetail | null>(null);
  const [saving, setSaving] = useState(false);
  const load = () => fetch(`/api/day-details?date=${date}`).then((response) => response.ok ? response.json() : Promise.reject()).then(setDetail);
  useEffect(() => { load().catch(() => setDetail(null)); }, [date]);
  const updateSchedule = (field: keyof DayDetail["fatherSchedule"], value: boolean | string) => setDetail((current) => current ? { ...current, fatherSchedule: { ...current.fatherSchedule, [field]: value } } : current);
  const save = async () => {
    if (!detail) return;
    setSaving(true);
    try {
      const response = await fetch("/api/day-details", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date, ...detail.fatherSchedule }) });
      if (!response.ok) throw new Error();
      setDetail(await response.json());
    } finally { setSaving(false); }
  };
  const schedule = detail?.fatherSchedule;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4"><Card className="w-full max-w-lg"><CardContent><div className="flex items-start justify-between"><div><p className="text-sm text-black/45">날짜 상세</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{date.replaceAll("-", ".")} 식단</h2></div><button onClick={close} className="text-xl text-black/35" aria-label="닫기">×</button></div>{!detail ? <p className="py-12 text-center text-sm text-black/45">불러오는 중...</p> : <><section className="mt-6 rounded-xl bg-[#f6f5f4] p-4"><p className="text-xs font-semibold tracking-[.08em] text-black/40">식단</p>{detail.meal ? <div className="mt-3 space-y-2 text-sm"><p><span className="text-black/45">점심</span> · {detail.meal.lunch ?? "계획 없음"}</p><p className="font-medium">주찬 · {detail.meal.main ?? "계획 없음"}</p>{detail.meal.sides.map((side) => <p key={side} className="text-black/65">부찬 · {side}</p>)}{detail.meal.baby && <p className="text-black/65">아기 · {detail.meal.baby}</p>}{detail.meal.note && <p className="pt-1 text-xs text-black/45">메모 · {detail.meal.note}</p>}</div> : <p className="mt-3 text-sm text-black/45">등록된 식단이 없습니다.</p>}</section><section className="mt-4 rounded-xl border border-black/[.08] p-4"><div><p className="text-xs font-semibold tracking-[.08em] text-black/40">아빠 일정</p><p className="mt-1 text-sm text-black/55">출근 및 식사 여부를 저장하면 다음 식단 검토에 반영됩니다.</p></div><div className="mt-4 space-y-3 text-sm"><label className="flex items-center justify-between"><span>출근</span><input type="checkbox" checked={schedule?.isWorking ?? false} onChange={(event) => updateSchedule("isWorking", event.target.checked)} className="h-4 w-4 accent-[#0075de]"/></label><label className={`flex items-center justify-between ${(schedule?.isWorking ?? false) ? "" : "text-black/30"}`}><span>회사에서 식사</span><input type="checkbox" disabled={!schedule?.isWorking} checked={schedule?.eatsAtCompany ?? false} onChange={(event) => updateSchedule("eatsAtCompany", event.target.checked)} className="h-4 w-4 accent-[#0075de]"/></label><label className="flex items-center justify-between"><span>집에서 저녁 미식사</span><input type="checkbox" checked={schedule?.isAway ?? false} onChange={(event) => updateSchedule("isAway", event.target.checked)} className="h-4 w-4 accent-[#0075de]"/></label><textarea value={schedule?.note ?? ""} onChange={(event) => updateSchedule("note", event.target.value)} className="h-20 w-full resize-none rounded-lg border border-black/[.12] p-3 text-sm outline-none focus:border-[#0075de]" placeholder="예: 토요일 출근, 점심 회사 식사"/></div><Button disabled={saving} onClick={save} className="mt-4 w-full">{saving ? "저장 중..." : "아빠 일정 저장"}</Button></section></>}</CardContent></Card></div>;
}
function AgentModal({ request, close }: { request: AgentRequest; close: () => void }) {
  const [prompt, setPrompt] = useState(request.prompt);
  const [message, setMessage] = useState("");
  const [result, setResult] = useState<DayUpdateResult | null>(null);
  const [loading, setLoading] = useState(false);
  const createPlan = async () => {
    if (!prompt.trim()) return;
    setLoading(true); setMessage(""); setResult(null);
    try {
      const response = await fetch("/api/agent/meal-plan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, action: request.action, date: request.date, weekStart: sundayFor(request.date), days: request.action === "UPDATE_DAY" ? 1 : 7 }) });
      const data = await response.json();
      setMessage(response.ok ? data.message : data.message ?? data.error ?? "Hermes 요청에 실패했습니다.");
      if (response.ok && data.result) setResult(data.result);
    } catch { setMessage("Hermes에 연결할 수 없습니다."); }
    finally { setLoading(false); }
  };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4"><Card className="w-full max-w-xl"><CardContent><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0d4]"><Sparkles className="text-[#e89d01]" size={20}/></div><button onClick={close} className="text-xl text-black/35">×</button></div><h2 className="mt-5 text-2xl font-semibold tracking-tight">Hermes에게 식단을 부탁해 보세요</h2><p className="mt-2 text-sm leading-5 text-black/55">{request.date ? `${request.date} 식단과 관련 레시피·장보기를 수정합니다.` : "이번 주 식단과 검증된 블로그 레시피·장보기를 준비합니다."}</p><textarea value={prompt} onChange={e => setPrompt(e.target.value)} className="mt-5 h-28 w-full resize-none rounded-lg border border-black/[.12] p-3 text-sm outline-none focus:border-[#0075de]"/><Button disabled={!prompt.trim() || loading} onClick={createPlan} className="mt-3 w-full"><Sparkles size={16}/>{loading ? "Hermes가 확인하고 있어요..." : "Hermes에 요청하기"}</Button>{message && <div className="mt-4 rounded-lg bg-[#e6f3fe] p-3 text-sm text-[#075f9f]">{message}</div>}{result && <div className="mt-4 grid gap-3 sm:grid-cols-2"><MealSnapshotCard label="변경 전" meal={result.before}/><MealSnapshotCard label={result.changed ? "변경 후" : "유지"} meal={result.after} highlight={result.changed}/></div>}<p className="mt-3 text-center text-[11px] text-black/40">완료된 변경은 레시피와 장보기 탭에도 자동으로 표시됩니다.</p></CardContent></Card></div>;
}

function sundayFor(date?: string) { const value = date ? new Date(`${date}T12:00:00+09:00`) : new Date(); value.setUTCDate(value.getUTCDate() - value.getUTCDay()); return value.toISOString().slice(0, 10); }
function shiftMonth(month: string, amount: number) { const [year, value] = month.split("-").map(Number); const date = new Date(Date.UTC(year, value - 1 + amount, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; }
function formatMonth(month: string) { const [year, value] = month.split("-"); return `${year}년 ${Number(value)}월`; }
function weekdayFor(date: string) { return ["일", "월", "화", "수", "목", "금", "토"][new Date(`${date}T12:00:00+09:00`).getUTCDay()]; }
function buildMonthDays(month: string) { const [year, value] = month.split("-").map(Number); const monthIndex = value - 1; const first = new Date(Date.UTC(year, monthIndex, 1)); const leading = first.getUTCDay(); const count = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate(); const length = Math.ceil((leading + count) / 7) * 7; return Array.from({ length }, (_, index) => { const date = new Date(Date.UTC(year, monthIndex, index - leading + 1)); return { date: date.toISOString().slice(0, 10), day: date.getUTCDate(), current: date.getUTCMonth() === monthIndex }; }); }
function MealSnapshotCard({ label, meal, highlight = false }: { label: string; meal: MealSnapshot | null; highlight?: boolean }) {
  return <div className={`rounded-xl border p-3 ${highlight ? "border-[#0075de]/30 bg-[#e6f3fe]" : "border-black/[.08] bg-white"}`}><p className="text-xs font-semibold text-black/40">{label}</p>{meal ? <><p className="mt-2 font-medium">주찬 · {meal.main}</p>{meal.sides.map((side) => <p key={side} className="mt-1 text-sm text-black/60">부찬 · {side}</p>)}{meal.baby && <p className="mt-2 text-xs text-black/50">아기 · {meal.baby}</p>}{meal.changeReason && <p className="mt-2 text-xs text-[#075f9f]">이유 · {meal.changeReason}</p>}</> : <p className="mt-2 text-sm text-black/45">식단 정보 없음</p>}</div>;
}
